from CONSTANT_POINTS1 import *
from CONSTANT_POINTS2 import *
from CONSTANT_POINTS3 import *
from CONSTANT_POINTS4 import *

CONSTANT_POINTS = CONSTANT_POINTS1 + CONSTANT_POINTS2 + CONSTANT_POINTS3 + CONSTANT_POINTS4